apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: vmcbom-services-public-k6-apiv1
  name: bom1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vmcbom-services-public-k6-apiv1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
      labels:
        app: vmcbom-services-public-k6-apiv1
    spec:
      containers:
      - env:
        - name: SPRING_CONFIG_LOCATION
          value: /mnt/property/vmcbom-services-public-k6-apiv1/application-pcs.properties
        - name: SPRING_PROFILES_ACTIVE
          value: pcs
        image: vmcbom-services-public-k6-apiv1
        imagePullPolicy: Never
        name: vmcbom-services-public-k6-apiv1
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "800Mi"
        volumeMounts:
        - mountPath: "/mnt"
          name: mnt-volume
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: mnt-volume
        hostPath:
          path: /run/desktop/mnt/host/c/mnt
          type: Directory
status: {}
