apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: bom2
  name: bom2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bom2
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
      labels:
        app: bom2
    spec:
      containers:
      - env:
        - name: SPRING_CONFIG_LOCATION
          value: /mnt/property/vmcbom-services-public-k6-v6-apiv1/application-pcs.properties
        - name: SPRING_PROFILES_ACTIVE
          value: pcs
        image: leixu1206/bom2:latest
        imagePullPolicy: ""
        name: bom2
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "1Gi"
        volumeMounts:
        - mountPath: "/mnt"
          name: mnt-volume
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: mnt-volume
        hostPath:
          path: /run/desktop/mnt/host/c/mnt
          type: Directory
status: {}
